#Указываем базовый образ
#FROM openjdk:22
#
## Устанавливаем Redis-сервер
#RUN apt-get update && apt-get install -y redis-server
#
## Копируем JAR-файл вашего Spring-приложения в контейнер
#COPY target/finalfinalback3.jar /app/finalfinalback3.jar
#
## Запускаем Redis-сервер и Spring-приложение
#CMD redis-server & java -jar /app/finalfinalback3.jar